### ISSUE TITLE
UI Development

### ISSUE THREAD

**Issue by Pmcslarrow** [simon-nstein/JournalingAppSP#1]
This is what I am assigning for you right now. Just get the UI to what you need it to look like!! Cheers

**Comment by simon-nstein** [comment]
Help Me!!!! -updated fixed

**Comment by simon-nstein** [comment]
Finished UI. Rose is the only one that has the UI updated, we should keep it that way. Lets just get that one working because Bud & Thorn are essentially the same so we can just copy them later.

**Comment by simon-nstein** [comment]
Also I need to rethink how the UI on how users will check their previous responses will work

**Comment by Pmcslarrow** [comment]
Sounds good I'll work with what's there soon

With regards to the history UI here are two ideas I saw on Dribbble 
1) we could create a simple menu navigation system that leads to another page
2) An example of how that page looks is down below

![image](https://user-images.githubusercontent.com/74205136/222790371-9e0098c8-b611-4b8d-b1be-089e55b039d6.png)

![image](https://user-images.githubusercontent.com/74205136/222790387-f56c9738-b33b-47b8-a672-b1340ed7cdf1.png)

**Comment by simon-nstein** [comment]
Hm yah I was looking up calendar stuff in Swift too. https://blog.logrocket.com/working-calendars-swift/
What are your thoughts on this, and then when they click on the date it will bring up what they typed

**Comment by simon-nstein** [comment]
Lets maybe chat about this so we can bring up each of our ideas

**Comment by Pmcslarrow** [comment]
I saw those too.  Do you want date picker or full screen (below)

![image](https://user-images.githubusercontent.com/74205136/222795204-7113c49e-187a-4e4c-9d58-ab976c31ac5a.png)

![image](https://user-images.githubusercontent.com/74205136/222795223-d9d0b16e-a74d-4e6b-bd2d-ad1c232c6eaa.png)

**Comment by simon-nstein** [comment]
After MVVM update we need to transfer old design to meet the need of MVVM requierments

**Comment by simon-nstein** [comment]
Small UI updates that can be seen on figma. Look at the section called 'New Rose', small changes.

**Comment by simon-nstein** [comment]
Update- This already happens, so resolved

Also something we need to keep in mind. If the user types a really long response(which they most likely will), on the home screen, in the rose box, it shouldn't show the whole response. It should be like 30 words max and then have dots after it(...).

**Comment by simon-nstein** [comment]
Small UI update to figma. Added images to each box. 
Note: The images will probably need to be made originally later on, these were just taken from internet, so probably some copyright issues or something. Just to keep in mind.

**Comment by Pmcslarrow** [comment]
The functionality is about all up to date for the Week Glance (almost). I would focus your efforts in adjusting the UI to look similar to how it all is on Figma if you can please.
