### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Pmcslarrow** [simon-nstein/JournalingAppSP#10]
After I complete the final task (atleast how it is seeming) and we finish the logo and gestures, I think it would be a good idea to implement testing software to test lots of aspects of our apps. 

It is good practice to learn testing. I have never done it, but it is extremely desirable for internships at bigger companies.

**Comment by simon-nstein** [comment]
We just need to use it and find issues lol - and have meelad and others mess around with it too just to find issues
