### ISSUE TITLE
Back arrow

### ISSUE THREAD

**Issue by Pmcslarrow** [simon-nstein/JournalingAppSP#6]
If you go into ContentView to look at the main page. You will notice that when you click onto the blue mindfulness journal, that this new navigation page has a back arrow that doesn't actually do anything. I was wondering if you knew where you put the code for this arrow and whether you could make its functionality work.  I placed a NavigationView around the vstack so that it would go back, but this clearly puts a "back" button. If you can figure out how to remove the arrow that is there right now and then replace the "back" button with an arrow that works too.

**Comment by simon-nstein** [comment]
Hmm weird. The button is stored in NavBar view and the 'dismiss()' part in the code usually makes it go back to the previous view if it's in a NavLink. I'll see if I can fix

**Comment by simon-nstein** [comment]
Fixed
